### PR TITLE
Bubbleplots

### PR DESCRIPTION
**Pull request by stuartskelton**
I submit a draft of the bubble plots for your consideration. It is a customised version of the XY graph.

### CODE REVIEW

**Comment by ranguard** [comment]
Wooo - thanks I'll have a look over the weekend

**Comment by ranguard** [comment]
Sorry, haven't forgotten, will try look at this early next week

**Comment by stuartskelton** [comment]
No worries.

I have been working on my next pr ;) I hope you'll like it as much as the
bubbles.

**Comment by ranguard** [comment]
I've merged those, let me know if you need a release, otherwise I'll wait
for your next PR :)

**Pull request merged**
